"""empty message

Revision ID: a1cb168b1a63
Revises: a5cffa318ac2
Create Date: 2026-04-04 20:00:29.548376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cb168b1a63'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('clima', sa.String(length=120), nullable=False),
    sa.Column('poblacion', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clima')
    )
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=False),
    sa.Column('id_planeta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_planeta'], ['planetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planeta_favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_planeta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_planeta'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personajes_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_personajes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_personajes'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('contrasena', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=False))
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha_registro')
        batch_op.drop_column('contrasena')
        batch_op.drop_column('nombre')

    op.drop_table('personajes_favoritos')
    op.drop_table('planeta_favorito')
    op.drop_table('personajes')
    op.drop_table('planetas')
    # ### end Alembic commands ###
