"""empty message

Revision ID: e2d4f35c21c2
Revises: a1cb168b1a63
Create Date: 2026-04-05 13:55:45.259476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d4f35c21c2'
down_revision = 'a1cb168b1a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes_favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_personaje', sa.Integer(), nullable=False))
        batch_op.drop_constraint('personajes_favoritos_id_personajes_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personajes', ['id_personaje'], ['id'])
        batch_op.drop_column('id_personajes')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.drop_constraint('planetas_clima_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.create_unique_constraint('planetas_clima_key', ['clima'])

    with op.batch_alter_table('personajes_favoritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_personajes', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('personajes_favoritos_id_personajes_fkey', 'personajes', ['id_personajes'], ['id'])
        batch_op.drop_column('id_personaje')

    # ### end Alembic commands ###
